name: AreYouTyping
version: '1.0'
main: me.orphey.areyoutypingplugin.AreYouTypingPlugin
api-version: '1.19'
depend: [HologramAPI, packetevents]
softdepend: [VaultAPI]
commands:
  areyoutyping:
    description: "AreYouTyping plugin main command"
    usage: "/areyoutyping <parameter>"
    aliases: [ayt]
    permission: ayt.admin
    permission-message: "You do not have ayt.admin permission"
permissions:
  ayt.admin:
    description: "Access to </ayt reload> command"
    default: op
  ayt.display:
    description: "Show chat typing hologram for the player"
    default: not op

